### ISSUE TITLE
Investigate database connection errors

### ISSUE THREAD

**Issue by sattlerc** [adeel/instiki2git#27]
Leaving server-side buffered queries running sometimes results in an aborted connection:
```
Traceback (most recent call last):
  File "/home/nlab/.local/bin/instiki2git", line 33, in <module>
    sys.exit(load_entry_point('instiki2git==0.2', 'console_scripts', 'instiki2git')())
  File "/home/nlab/.local/lib/python3.9/site-packages/instiki2git/cli.py", line 446, in cli
    load_commit_and_push(
  File "/home/nlab/.local/lib/python3.9/site-packages/instiki2git/cli.py", line 334, in load_commit_and_push
    git_commit(
  File "/home/nlab/.local/lib/python3.9/site-packages/instiki2git/cli.py", line 119, in git_commit
    for (path, obj) in entries:
  File "/home/nlab/.local/lib/python3.9/site-packages/instiki2git/cli.py", line 316, in entries
    for revision in revisions:
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 429, in fetchone
    row = self.read_next()
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 424, in read_next
    return self._conv_row(self._result._read_rowdata_packet_unbuffered())
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1244, in _read_rowdata_packet_unbuffered
    packet = self.connection._read_packet()
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 711, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 748, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
Exception ignored in: <function SSCursor.close at 0x7f10b4e7c160>
Traceback (most recent call last):
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 401, in close
    self._result._finish_unbuffered_query()
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1261, in _finish_unbuffered_query
    packet = self.connection._read_packet()
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 729, in _read_bytes
    self._sock.settimeout(self._read_timeout)
AttributeError: 'NoneType' object has no attribute 'settimeout'
Exception ignored in: <function MySQLResult.__del__ at 0x7f10b4d22c10>
Traceback (most recent call last):
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1152, in __del__
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1261, in _finish_unbuffered_query
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 692, in _read_packet
  File "/home/nlab/.local/lib/python3.9/site-packages/pymysql/connections.py", line 729, in _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'
```

MariaDB Server log:
```
2022-10-22 23:13:30 4076268 [Warning] Aborted connection 4076268 to db: 'nlab' user: 'nlab' host: 'localhost' (Got an error writing communication packets)
```

**Comment by sattlerc** [comment]
As a workaround, one could divide an HTML commit into smaller commits of fixed numbers of page updated, e.g. 100.

**Comment by sattlerc** [comment]
The errors don't seem to appear anymore after going back to the previous HTML mode query in 3f7f841. If someone wants to test, use HTML mode in 6f215ff.
